# https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  pull_request:
  push:
    branches:
      - master
  release:

jobs:
  run_tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        # Keep the version here in sync with the ones used in noxfile.py
        python-version: ["3.7", "3.10"]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nox
      - name: Install gdb ubuntu
        run: |
          sudo apt-get install gdb
      - name: Execute Tests
        run: |
          nox --non-interactive --session tests-${{ matrix.python-version }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nox
      - name: Lint
        run: |
          nox --non-interactive --session lint

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nox
      - name: Verify Docs
        run: |
          nox --non-interactive --session docs
